apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: setup
        image: busybox
        command: ["/bin/sh", "-c", "/init-scripts/setup.sh"]
        volumeMounts:
        - name: init-scripts
          mountPath: /init-scripts
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "5"
        volumeMounts:
        - mountPath: /opt/sonarqube/data
          name: sonarqube-storage
      volumes:
      - name: sonarqube-storage
        persistentVolumeClaim:
          claimName: sonarqube-pvc
      - name: init-scripts
        emptyDir: {}

