apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sonarqube
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30001  # Puerto NodePort para PostgreSQL
  selector:
    app: postgres
