apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/postgresql
    server: 192.168.10.17
